server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình thêm để tránh lỗi cache cho các file static nếu cần
    location ~* \.(?:css|js|map|jpe?g|png|gif|ico)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public";
    }
}
