server {
    listen 80;
    server_name ai-interview.id.vn www.ai-interview.id.vn;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend service
    location /api {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Cache static files
    location ~* \.(?:css|js|map|jpe?g|png|gif|ico)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public";
    }
}
