name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "--- UPDATING USER BACKEND ---"
            cd /var/www/ai-interview-user/user-backend
            git pull origin main
            
            # Tạo file .env cho Backend
            echo "PORT=5000" > .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "NODE_ENV=production" >> .env
            
            npm install
            npm run build
            pm2 delete user-api || true
            pm2 start dist/server.js --name "user-api"

            echo "--- UPDATING USER FRONTEND ---"
            cd /var/www/ai-interview-user/user-frontend
            git pull origin main
            echo "VITE_API_URL=http://${{ secrets.HOST }}:5000" > .env
            npm install
            rm -rf dist
            npm run build
            
            # Cung cấp lệnh để Nginx nhận diện file mới nếu cần (tùy cấu hình)
            # sudo systemctl restart nginx
            
            echo "--- DEPLOY SUCCESSFUL ---"
